ERROR 2024-09-03 19:42:43,504 log Internal Server Error: /blogs/
Traceback (most recent call last):
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: blog_blog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\blog\blog\views.py", line 26, in blog_post_list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: blog_blog
ERROR 2024-09-03 19:42:43,520 basehttp "GET /blogs/ HTTP/1.1" 500 23252
ERROR 2024-09-03 19:46:58,238 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:46:58,238 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:49:03,648 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:49:03,660 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:50:27,324 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:50:27,324 basehttp "GET /blogs/ HTTP/1.1" 500 75
ERROR 2024-09-03 19:51:00,609 log Internal Server Error: /blogs/
Traceback (most recent call last):
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: blog_blog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\blog\blog\views.py", line 26, in blog_post_list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Shailendra Shetty3\Django_Projects\blog\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: blog_blog
ERROR 2024-09-03 19:51:00,624 basehttp "GET /blogs/ HTTP/1.1" 500 23255
ERROR 2024-09-03 19:53:54,581 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:53:54,581 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:55:32,572 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:55:32,573 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:56:44,380 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:56:44,381 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:56:45,955 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:56:45,956 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:56:58,234 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:56:58,234 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:57:00,516 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:57:00,516 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:58:22,358 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:58:22,358 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:58:31,317 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:58:31,317 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 19:59:44,824 log Internal Server Error: /blogs/
ERROR 2024-09-03 19:59:44,824 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 20:03:24,576 log Internal Server Error: /blogs/
ERROR 2024-09-03 20:03:24,576 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 20:05:05,541 log Internal Server Error: /blogs/
ERROR 2024-09-03 20:05:05,541 basehttp "POST /blogs/ HTTP/1.1" 500 37
ERROR 2024-09-03 20:06:45,512 log Internal Server Error: /blogs/
ERROR 2024-09-03 20:06:45,512 basehttp "GET /blogs/ HTTP/1.1" 500 40
ERROR 2024-09-03 20:06:57,961 log Internal Server Error: /blogs/
ERROR 2024-09-03 20:06:57,961 basehttp "GET /blogs/ HTTP/1.1" 500 40
